// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.2.1
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Financial.Spec
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.2.1")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Creación de Creditos")]
    public partial class CreacionDeCreditosFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Loan.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("es-ES"), "Creación de Creditos", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Crear un Credito con Capital Cero")]
        public virtual void CrearUnCreditoConCapitalCero()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Crear un Credito con Capital Cero", ((string[])(null)));
#line 5
this.ScenarioSetup(scenarioInfo);
#line 7
testRunner.Given("un Nuevo Credito", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 8
testRunner.When("el Capital es Menor o Igual que Cero", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Cuando ");
#line 9
testRunner.Then("debe lanzar una Exception CapitalZeroNotAllowedException", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entonces ");
#line 11
testRunner.Given("un Nuevo Crédito", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 12
testRunner.When("el interes es Menor o Igual que Cero", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Cuando ");
#line 13
testRunner.Then("debe lanzar una Exception InvalidRateException", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entonces ");
#line 15
testRunner.Given("un Nuevo Crédito", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 16
testRunner.When("el plazo es Menor o Igual que Cero", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Cuando ");
#line 17
testRunner.Then("debe lanzar una Exception InvalidTermException", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entonces ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
